name: ads_sample_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.2 <4.0.0'
# This app was created with Flutter v3.16.2 - Dart v3.2.2 - Devtool v2.28.3

dependencies:
  flutter:
    sdk: flutter

  easy_ads_flutter:
    path: ./packages/easy-ad
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true