name: easy_ads_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  google_mobile_ads: ^4.0.0

  collection: ^1.17.2
  logger: ^2.0.2
  visibility_detector: ^0.4.0+2
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.1
  applovin_max:
    path: ./packages/applovin_max

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.zens.easy_ad
        pluginClass: EasyAdPlugin
      ios:
        pluginClass: EasyAdPlugin
